/**
 * Main-process access to the bundled Aqua Nuqi brand artwork.
 *
 * The renderer imports brand images through Vite (`@renderer/brand`). The main
 * process cannot, so it reads them off disk here. This is the only module that
 * knows where the files live; everything else asks by logical name.
 *
 * Artwork is generated by `scripts/generate-brand-assets.py` from a single
 * source file — see `src/shared/brand.ts`.
 */

import fs from 'node:fs'
import path from 'node:path'
import { BRAND_ASSETS } from '@shared/brand'

/** Files the main process embeds, beyond the shared set. */
export const MAIN_BRAND_ASSETS = {
  /** Small lockup base64-embedded into generated PDFs. */
  logoPrint: 'logo-print.png',
} as const

const dataUrlCache = new Map<string, string | null>()
const pathCache = new Map<string, string | null>()

/**
 * Locate a file under `resources/brand/`.
 *
 * Layouts that must all work:
 * - dev / vitest        → `<repo>/resources/brand`
 * - packaged (asar off) → `<install>/resources/app/resources/brand`
 * - bundled out/main    → `<…>/out/main/../../resources/brand`
 * - extraResources      → `<install>/resources/brand`
 *
 * `roots` lets callers pass Electron's `app.getAppPath()` and
 * `process.resourcesPath`, which are unavailable under vitest.
 */
export function resolveBrandAssetPath(fileName: string, roots: string[] = []): string | null {
  const cacheKey = `${fileName}::${roots.join('|')}`
  const cached = pathCache.get(cacheKey)
  if (cached !== undefined) return cached

  const candidates = [
    ...roots.flatMap((root) => [
      path.join(root, 'brand', fileName),
      path.join(root, 'resources', 'brand', fileName),
      path.join(root, 'app', 'resources', 'brand', fileName),
    ]),
    path.join(__dirname, '../../resources/brand', fileName),
    path.join(__dirname, '../../../resources/brand', fileName),
    path.join(process.cwd(), 'resources', 'brand', fileName),
  ]

  const found = candidates.find((candidate) => fs.existsSync(candidate)) ?? null
  const resolved = found ? path.resolve(found) : null
  pathCache.set(cacheKey, resolved)
  return resolved
}

const MIME_BY_EXT: Record<string, string> = {
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  svg: 'image/svg+xml',
  webp: 'image/webp',
  gif: 'image/gif',
  bmp: 'image/bmp',
}

export function fileToDataUrl(filePath: string): string | null {
  try {
    if (!fs.existsSync(filePath)) return null
    const ext = path.extname(filePath).toLowerCase().replace('.', '')
    const mime = MIME_BY_EXT[ext] ?? 'image/png'
    return `data:${mime};base64,${fs.readFileSync(filePath).toString('base64')}`
  } catch {
    return null
  }
}

/**
 * Base64 data URL for a bundled brand asset.
 *
 * Cached: a 300-invoice batch would otherwise re-read and re-encode the same
 * file 300 times.
 */
export function brandAssetDataUrl(fileName: string, roots: string[] = []): string | null {
  const cacheKey = `${fileName}::${roots.join('|')}`
  const cached = dataUrlCache.get(cacheKey)
  if (cached !== undefined) return cached

  const filePath = resolveBrandAssetPath(fileName, roots)
  const dataUrl = filePath ? fileToDataUrl(filePath) : null
  dataUrlCache.set(cacheKey, dataUrl)
  return dataUrl
}

/** Print-optimised lockup embedded in PDFs when no business logo is uploaded. */
export function brandPrintLogoDataUrl(roots: string[] = []): string | null {
  return brandAssetDataUrl(MAIN_BRAND_ASSETS.logoPrint, roots)
}

/** Lockup for the fatal-error window, which renders from an inline HTML string. */
export function brandLogoDataUrl(roots: string[] = []): string | null {
  return brandAssetDataUrl(BRAND_ASSETS.logoFull, roots)
}

/**
 * Window icon path. Packaged builds get their icon from electron-builder, but
 * setting it explicitly gives dev runs the real icon instead of Electron's.
 */
export function appIconPath(roots: string[] = []): string | null {
  const fileName = process.platform === 'win32' ? 'icon.ico' : 'icon.png'
  const candidates = [
    ...roots.flatMap((root) => [
      path.join(root, fileName),
      path.join(root, 'resources', fileName),
      path.join(root, 'app', 'resources', fileName),
    ]),
    path.join(__dirname, '../../resources', fileName),
    path.join(__dirname, '../../../resources', fileName),
    path.join(process.cwd(), 'resources', fileName),
  ]
  const found = candidates.find((candidate) => fs.existsSync(candidate))
  return found ? path.resolve(found) : null
}

/** Test seam. */
export function __clearBrandAssetCache(): void {
  dataUrlCache.clear()
  pathCache.clear()
}
